version: "3.7"

services:
  server:
    build:
      context: ./nestjs-server/server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/test
      - JWT_SECRET=mysecretkey
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - JPP_SRV_BASE_URL=http://server:5000
    environment:
      - JPP_SRV_BASE_URL=http://server:5000
    depends_on:
      - db
      - server
    # volumes:
    #   - ./client/nginx.conf.template:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_volume:/data/db
  db-admin:
    image: mongo-express
    depends_on:
      - db
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db

volumes:
  db_volume:
    name: "mongodb_jpp_e2e"
