version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  deploy-to-heroku:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Create client distribution
          command: cd scripts && nvm install 10.15.3 && nvm use 10.15.3 && npm version && sh prepareClientAppDistribution.sh
      - run:
          name: Push to Heroku
          command: |
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              cd server
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web --arg NODE_CONFIG='{"mongoURI":"${PROD_DB_URI}", "jwtSecret":"${PROD_JWT_SECRET}"}'
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web
              
workflows:
    deploy-to-heroku:
      jobs:
        - deploy-to-heroku
            #filters:
            #    branches:
            #      only:
            #        - master
