version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  create-docker-image:
    working_directory: ~/server
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Create client distribution
          command: |
              cd scripts
              sh prepareClientAppDistribution
      - run:
          name: Install Heroku CLI and login
          command: |
              sudo curl https://cli-assets.heroku.com/install.sh
      - run:
          name: Create Docker image for the server
          command: |
              sh
              cd sever
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME}
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web
              
workflows:
    create-docker-image:
      jobs:
        - create-docker-image:
            filters:
                branches:
                  only:
                    - master
