version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  deploy-to-heroku:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      DB: "{\"mongoURI\":\"$PROD_DB_URI\", \"jwtSecret\":\"$PROD_JWT_SECRET\"}"
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo $DB
      - run:
          name: Check node version before
          command: | 
            node -v
      - run:
          name: Install NVM
          command: | 
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Install new node version
          command: | 
            nvm --version
            nvm install 10.15.3
      - run:
          name: Check node version after
          command: | 
            node -v
      - run:
          name: Create client distribution
          command: cd scripts && nvm use 10.15.3 && sh prepareClientAppDistribution.sh
      - run:
          name: Push to Heroku
          command: |
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              cd server
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web --arg NODE_CONFIG='{"mongoURI":"$PROD_DB_URI", "jwtSecret":"$PROD_JWT_SECRET"}'
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web
              
workflows:
    deploy-to-heroku:
      jobs:
        - deploy-to-heroku
            #filters:
            #    branches:
            #      only:
            #        - master
