version: "3.7"

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_volume:/data/db
  db-admin:
    image: mongo-express
    depends_on:
      - db
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db

volumes:
  db_volume:  
    name: "mongodb_jpp_new"
