name: Run tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v4
    - run: cd server
    - run: npm ci
    - run: npm test
